# Generated by Django 3.2.6 on 2021-08-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='claps',
            field=models.IntegerField(default=0),
        ),
    ]
